### ISSUE TITLE
Encountered error downloading depot manifest 221381 4335511437511540287: NotFound

### ISSUE THREAD

**Issue by jasonpau** [gregstein/HDDowngradeTool#1]
When trying to downgrade, I'm getting the following error in my terminal:
 
```
Using filelist: 'C:\Users\Jason\AppData\Roaming\HD Downgrade Tool\exclude.txt'.
Connecting to Steam3... Done!
Logging '[my_steam_account]' into Steam3... Done!
Using Steam3 suggested CellID: 64
Got 12 licenses for account!
Got session token!
Got AppInfo for 221380
Using app branch: 'Public'.
Got depot key for 221381 result: OK
Downloading depot 221381 - Age2HD Content
Downloading depot manifest...Got CDN auth token for steamcontent.com result: OK (expires 12/14/2020 1:54:58 AM)
Encountered error downloading depot manifest 221381 4335511437511540287: NotFound
Encountered error downloading depot manifest 221381 4335511437511540287: NotFound
Encountered error downloading depot manifest 221381 4335511437511540287: NotFound
Encountered error downloading depot manifest 221381 4335511437511540287: NotFound
Encountered error downloading depot manifest 221381 4335511437511540287: NotFound
...
```

It just repeats that error over and over till I manually stop it with CTRL + C.

I tried the downgrade with `6 September 2018 (3062235)` and `20 June 2017 (1832983)` and both gave the same kind of error. (The long number at the end was different, but other than that it looked the same.)

Not sure if it makes any difference, but I'm running Windows 10 Home. If any other diagnostic steps are needed let me know and I'll try to find time to test and document.

**Comment by gregstein** [comment]
Sorry Just noticed this issue today.
To fix
☑Install .NET RUNTIME 6 https://dotnet.microsoft.com/download/dotnet/6.0
☑Download latest downgrade tool https://github.com/gregstein/HDDowngradeTool
